DROP TABLE IF EXISTS SILVER1.PCDEM_CLEAN;
GO

CREATE TABLE SILVER1.PCDEM_CLEAN (
    ACH_DATE DATE,
    REGION_ODS_CODE VARCHAR(50),
    REGION_ONS_CODE VARCHAR(50),
    REGION_NAME VARCHAR(500),
    ICB_ODS_CODE VARCHAR(50),
    ICB_ONS_CODE VARCHAR(50),
    ICB_NAME VARCHAR(500),
    SUB_ICB_ODS_CODE VARCHAR(100),
    SUB_ICB_ONS_CODE VARCHAR(100),
    SUB_ICB_NAME VARCHAR(1000),
    Measure VARCHAR(100),
    Value INT
);
GO

INSERT INTO SILVER1.PCDEM_CLEAN
SELECT
    TRY_CAST(ACH_DATE AS DATE),
    REGION_ODS_CODE,
    REGION_ONS_CODE,
    REGION_NAME,
    ICB_ODS_CODE,
    ICB_ONS_CODE,
    ICB_NAME,
    SUB_ICB_ODS_CODE,
    SUB_ICB_ONS_CODE,
    SUB_ICB_NAME,
    Measure,
    Value
FROM BRONZE1.PCDEM_RAW;
GO
