DROP TABLE IF EXISTS SILVER1.MYE2_CLEAN;
GO

CREATE TABLE SILVER1.MYE2_CLEAN (
    LA_Code VARCHAR(20),
    Geography VARCHAR(200),
    Age VARCHAR(10),
    Population INT
);
GO

INSERT INTO SILVER1.MYE2_CLEAN
SELECT
    LTRIM(RTRIM(LA_Code)),
    LTRIM(RTRIM(Geography)),
    LTRIM(RTRIM(Age)),
    Population
FROM BRONZE1.MYE2_RAW;
GO
