DROP TABLE IF EXISTS SILVER1.LSOA_TO_SICBL_LAD;
GO

CREATE TABLE SILVER1.LSOA_TO_SICBL_LAD (
    LSOA21CD VARCHAR(MAX),
    LSOA21NM VARCHAR(MAX),
    SICBL23CD VARCHAR(MAX),
    SICBL23CDH VARCHAR(MAX),
    SICBL23NM VARCHAR(MAX),
    ICB23CD VARCHAR(MAX),
    ICB23CDH VARCHAR(MAX),
    ICB23NM VARCHAR(MAX),
    LAD23CD VARCHAR(MAX),
    LAD23NM VARCHAR(MAX)
);
GO

INSERT INTO SILVER1.LSOA_TO_SICBL_LAD
SELECT
    LTRIM(RTRIM(LSOA21CD)),
    LTRIM(RTRIM(LSOA21NM)),
    LTRIM(RTRIM(SICBL23CD)),
    LTRIM(RTRIM(SICBL23CDH)),
    LTRIM(RTRIM(SICBL23NM)),
    LTRIM(RTRIM(ICB23CD)),
    LTRIM(RTRIM(ICB23CDH)),
    LTRIM(RTRIM(ICB23NM)),
    LTRIM(RTRIM(LAD23CD)),
    LTRIM(RTRIM(LAD23NM))
FROM BRONZE1.LA_ICB_LOOKUP_RAW;
GO
