DROP TABLE IF EXISTS GOLD1.Population_By_LA;
GO

SELECT
    LA_Code,
    SUM(CAST(Population AS BIGINT)) AS Total_Population,
    SUM(CASE WHEN TRY_CAST(Age AS INT) >= 65 THEN Population END) AS Age65Plus,
    SUM(CASE WHEN TRY_CAST(Age AS INT) BETWEEN 0 AND 14 THEN Population END) AS Children_0_14,
    SUM(CASE WHEN TRY_CAST(Age AS INT) BETWEEN 15 AND 64 THEN Population END) AS Working_Age_15_64
INTO GOLD1.Population_By_LA
FROM SILVER1.MYE2_CLEAN
GROUP BY LA_Code;
GO
