DROP TABLE IF EXISTS BRONZE1.MYE2_RAW;
GO

CREATE TABLE BRONZE1.MYE2_RAW (
    LA_Code VARCHAR(20),
    Geography VARCHAR(200),
    Age VARCHAR(10),
    Population INT
);
GO

BULK INSERT BRONZE1.MYE2_RAW
FROM 'C:\temp2\mye2.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    TABLOCK,
    CODEPAGE = '65001'
);
GO
