DROP TABLE IF EXISTS BRONZE1.PCDEM_RAW;
GO

CREATE TABLE BRONZE1.PCDEM_RAW (
    ACH_DATE VARCHAR(50),
    REGION_ODS_CODE VARCHAR(50),
    REGION_ONS_CODE VARCHAR(50),
    REGION_NAME VARCHAR(500),
    ICB_ODS_CODE VARCHAR(50),
    ICB_ONS_CODE VARCHAR(50),
    ICB_NAME VARCHAR(500),
    SUB_ICB_ODS_CODE VARCHAR(100),
    SUB_ICB_ONS_CODE VARCHAR(100),
    SUB_ICB_NAME VARCHAR(1000),
    Measure VARCHAR(100),
    Value INT
);
GO

BULK INSERT BRONZE1.PCDEM_RAW
FROM 'C:\temp2\pcdem-sicbl-age-sex-oct-2025.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    TABLOCK,
    CODEPAGE = '65001'
);
GO
