DROP TABLE IF EXISTS BRONZE1.LA_ICB_LOOKUP_RAW;
GO

CREATE TABLE BRONZE1.LA_ICB_LOOKUP_RAW (
    LSOA21CD VARCHAR(MAX),
    LSOA21NM VARCHAR(MAX),
    SICBL23CD VARCHAR(MAX),
    SICBL23CDH VARCHAR(MAX),
    SICBL23NM VARCHAR(MAX),
    ICB23CD VARCHAR(MAX),
    ICB23CDH VARCHAR(MAX),
    ICB23NM VARCHAR(MAX),
    LAD23CD VARCHAR(MAX),
    LAD23NM VARCHAR(MAX),
    ObjectId INT
);
GO

BULK INSERT BRONZE1.LA_ICB_LOOKUP_RAW
FROM 'C:\temp2\LSOA_(2021)_to_SICBL_to_ICB_to_LAD_(April_2023)_Lookup_in_EN.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    TABLOCK,
    CODEPAGE = '65001'
);
GO
